[versions]
tcg-mapper = "0.2.0"
yaml-serializer = "0.13.0"

[libraries]
tcg-mapper = { module = "eu.codlab:tcg-mapper", version.ref = "tcg-mapper" }
yaml-serializer = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yaml-serializer" }
